apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sampleapp
  labels:
    release: rls-sample-app
spec:
  selector:
    matchLabels:
      app: sampleapp
  podMetricsEndpoints:
  - port: metrics
