# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  imageName: dongkun-canary-test
  dockerRegistryServiceConnection: sharedServiceConnection
  imageRepository: 'dongkun-canary-test'
  containerRegistry: sharedglobalservices.azurecr.io
  tag: '$(Build.BuildId)'
  secretName: "mysecret"
  azureSubscriptionEndpoint: PromoteIQ-Playground (b558a354-8f0b-4461-8876-9d1e8b56360f)
  azureResourceGroup: dev-grf-del-iad-rg
  kubernetesCluster: dev-grf-del-iad-aks
  partitionValueFirstPromote: 8
  partitionValueSecondPromote: 5
  partitionValueThirdPromote: 2
  partitionValueFinalPromote: 0


stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Docker@2
          displayName: Build and push image
          inputs:
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageName)
            command: buildAndPush
            Dockerfile: app/Dockerfile
            tags: |
              $(tag)

        - task: HelmInstaller@0
          displayName: install helm
          inputs:
            helmVersion: "v3.7.1"
            installKubectl: false
            checkLatestHelmVersion: false

        - script: |
            export HELM_EXPERIMENTAL_OCI=1
            helm registry login sharedglobalservices.azurecr.io --username SharedGlobalServices --password ISkbz+F/5+s6eTfFagmVVHA2Wm03Zv0q
            helm package $(System.DefaultWorkingDirectory)/helm/app
            helm push sample-app-0.0.1.tgz oci://sharedglobalservices.azurecr.io/delivery/helm
          displayName: build helm chart

        - upload: manifests
          artifact: manifests

        - upload: misc
          artifact: misc

#        - task: Kubernetes@1
#          displayName: kubectl get pods number
#          inputs:
#            connectionType: Azure Resource Manager
#            azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
#            azureResourceGroup: $(azureResourceGroup)
#            kubernetesCluster: $(kubernetesCluster)
#            command: get
#            arguments: statefulset sampleapp -n dongkun -o jsonpath='{ .spec.replicas }'

        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureSubscriptionEndpoint)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az aks get-credentials -g $(azureResourceGroup) -n $(kubernetesCluster) --admin
              describe=`kubectl get statefulset sampleapp -n dongkun -o jsonpath="{ .spec.replicas }"`
              echo "++++++++++++++++++++++++++++++++++++++++++++++"
              echo "$describe"
              echo "=============================================="
              echo `kubectl get statefulset sampleapp -n dongkun -o jsonpath="{ .spec.replicas }"`
              echo "=============================================="
              echo "##vso[task.setvariable variable=podsNumber;isoutput=true]$describe"
          displayName: get pods number
          name: GetPodsNum

        - bash: |
            echo $( GetPodsNum.podsNumber)
          displayName: show pods number
          name: ShowPodsNumber

- stage: DeployFirst
  displayName: Deploy first
  dependsOn: Build
  condition: succeeded()

  jobs:
    - deployment: helmDeploy
      displayName: deploy app by helm
      environment: "dongkun-canarytest.dongkun"

      strategy:
        runOnce:
          deploy:
            steps:
              - script: |
                  export HELM_EXPERIMENTAL_OCI=1
                  helm registry login sharedglobalservices.azurecr.io --username SharedGlobalServices --password ISkbz+F/5+s6eTfFagmVVHA2Wm03Zv0q
                  helm pull oci://sharedglobalservices.azurecr.io/delivery/helm/sample-app --version 0.0.1
                displayName: pull helm chart

              - task: KubernetesManifest@0
                displayName: create secret
                inputs:
                  action: createSecret
                  secretName: $(secretName)
                  dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

              - task: HelmDeploy@0
                displayName: do deploy
                inputs:
                  connectionType: "Azure Resource Manager"
                  azureSubscription: $(azureSubscriptionEndpoint)
                  azureResourceGroup: $(azureResourceGroup)
                  kubernetesCluster: $(kubernetesCluster)
                  namespace: dongkun
                  useClusterAdmin: true
                  command: upgrade
                  chartType: filepath
                  chartPath: $(System.DefaultWorkingDirectory)/sample-app-0.0.1.tgz
                  releaseName: rls-sample-app
                  install: true
                  waitForExecution: false
                  arguments: >
                    --cleanup-on-fail
                    --set imagePullSecrets=$(secretName)
                    --set buildId=$(tag)



#  jobs:
#    - deployment: Deploycanary
#      displayName: Deploy canary
#      pool:
#        vmImage: ubuntu-latest
#      environment: 'dongkun-canarytest.dongkun'
#      strategy:
#        runOnce:
#          deploy:
#            steps:
#              - task: KubernetesManifest@0
#                displayName: Create imagePullSecret
#                inputs:
#                  action: createSecret
#                  secretName: azure-pipelines-canary-k8s
#                  dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
#
#              - task: KubernetesManifest@0
#                displayName: Deploy to Kubernetes cluster
#                env:
#                  PARTITION_VALUE: 4
#                inputs:
#                  action: 'deploy'
##                  strategy: "canary"
##                  percentage: "25"
#                  manifests: |
#                    $(Pipeline.Workspace)/manifests/*
#                  containers: '$(containerRegistry)/$(imageRepository):$(tag)'
#                  imagePullSecrets: azure-pipelines-canary-k8s
#
#              - task: KubernetesManifest@0
#                displayName: Deploy Forbio and Service Monitor
#                inputs:
#                  action: 'deploy'
#                  manifests: |
#                    $(Pipeline.Workspace)/misc/*
#



- stage: promote1
  displayName: promote stage
  dependsOn: DeployFirst
  condition: succeeded()

  jobs:
    - template: templates/helm-deploy.yml
      parameters:
        partitionValue: $(partitionValueFirstPromote)
        buildId: $(tag)
        secretName: $(secretName)

#  jobs:
#    - deployment: promote
#      displayName: promote deploy
#      pool:
#        vmImage: ubuntu-latest
#      environment: 'dongkun-canarytest.dongkun'
#      strategy:
#        runOnce:
#          deploy:
#            steps:
#              - task: KubernetesManifest@0
#                displayName: promote partition rolling update
#                env:
#                  PARTITION_VALUE: 2
#                inputs:
#                  action: 'deploy'
#                  manifests: $(Pipeline.Workspace)/manifests/deployment.yml
#                  containers: '$(containerRegistry)/$(imageRepository):$(tag)'
#                  imagePullSecrets: azure-pipelines-canary-k8s



#
#- stage: PromoteRejectCanary
#  displayName: Promote or Reject canary
#  dependsOn: DeployCanary
#  condition: succeeded()
#
#  jobs:
#  - deployment: PromoteCanary
#    displayName: Promote Canary
#    pool:
#      vmImage: ubuntu-latest
#    environment: 'dongkun-canarytest.dongkun'
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - task: KubernetesManifest@0
#            displayName: promote canary
#            inputs:
#              action: 'promote'
#              strategy: 'canary'
#              manifests: '$(Pipeline.Workspace)/manifests/*'
#              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
#              imagePullSecrets: '$(imagePullSecret)'
#
#- stage: RejectCanary
#  displayName: Reject canary
#  dependsOn: PromoteRejectCanary
#  condition: failed()
#
#  jobs:
#  - deployment: RejectCanary
#    displayName: Reject Canary
#    pool:
#      vmImage: ubuntu-latest
#    environment: 'dongkun-canarytest.dongkun'
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - task: KubernetesManifest@0
#            displayName: reject canary
#            inputs:
#              action: 'reject'
#              strategy: 'canary'
#              manifests: '$(Pipeline.Workspace)/manifests/*'

- stage: promote2
  displayName: second promote stage
  dependsOn: promote1
  condition: succeeded()

  jobs:
    - template: templates/helm-deploy.yml
      parameters:
        partitionValue: $(partitionValueSecondPromote)
        buildId: $(tag)
        secretName: $(secretName)

- stage: promote3
  displayName: third promote stage
  dependsOn: promote2
  condition: succeeded()

  jobs:
    - template: templates/helm-deploy.yml
      parameters:
        partitionValue: $(partitionValueThirdPromote)
        buildId: $(tag)
        secretName: $(secretName)

- stage: finalPromote
  displayName: final promote
  dependsOn: promote3
  condition: succeeded()

  jobs:
    - template: templates/helm-deploy.yml
      parameters:
        partitionValue: $(partitionValueFinalPromote)
        buildId: $(tag)
        secretName: $(secretName)