apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  serviceName: "Sample-App"
  minReadySeconds: 10
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: sampleapp
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sampleapp
        #replace <foobar> with your container registry. Example: contosodemo.azurecr.io
        image: sharedglobalservices.azurecr.io/dongkun-canary-test
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
