parameters:
  - name: partitionValue
  - name: buildId
  - name: secretName
  - name: podNumber

jobs:
  - deployment: helmInit
    displayName: init
    environment: "dongkun-canarytest.dongkun"
    variables:
      partition: ${{ parameters.partitionValue }}
      podNumber: ${{ parameters.podNumber }}
      buildId: ${{ parameters.buildId }}
      secretname: ${{ parameters.secretName }}

    strategy:
      runOnce:
        deploy:
          steps:
#            - script: |
#                export HELM_EXPERIMENTAL_OCI=1
#                helm registry login sharedglobalservices.azurecr.io                                                                                  --username SharedGlobalServices --password ISkbz+F/5+s6eTfFagmVVHA2Wm03Zv0q
#                helm pull oci://sharedglobalservices.azurecr.io/delivery/helm/sample-app --version 0.0.1 --destination $(System.DefaultWorkingDirectory)
#              displayName: pull helm chart

            - task: AzureCLI@2
              env:
                HELM_EXPERIMENTAL_OCI: 1
              displayName: pull helm chart safely
              inputs:
                azureSubscription: PromoteIQ-Playground (b558a354-8f0b-4461-8876-9d1e8b56360f)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  ACCESS_TOKEN=$(az acr login --name sharedglobalservices.azurecr.io --expose-token --output tsv --query accessToken)
                  echo $ACCESS_TOKEN | helm registry login sharedglobalservices.azurecr.io -u 00000000-0000-0000-0000-000000000000 --password-stdin
                  helm pull oci://sharedglobalservices.azurecr.io/delivery/helm/sample-app --version 0.0.1


            - bash: |
                ls $(System.DefaultWorkingDirectory)

            - bash: |
                truePercent=$((100-$(partition)))
                truePodNumber=$(podNumber)
                echo $truePodNumber
                truePartition1=$(($truePercent*$truePodNumber))
                echo $truePartition1
                truePartition=$(($truePartition1/100))
                echo $truePartition
                echo "##vso[task.setVariable variable=truePartition;isoutput=true]$truePartition"
              name: GetPartition1
              displayName: calculate partition

            - bash: |
                ls $(System.DefaultWorkingDirectory)
            - task: HelmDeploy@0
              displayName: do deploy
              inputs:
                connectionType: "Azure Resource Manager"
                azureSubscription: PromoteIQ-Playground (b558a354-8f0b-4461-8876-9d1e8b56360f)
                azureResourceGroup: dev-grf-del-iad-rg
                kubernetesCluster: dev-grf-del-iad-aks
                namespace: dongkun
                useClusterAdmin: true
                command: upgrade
                chartType: filepath
                chartPath: $(System.DefaultWorkingDirectory)/sample-app-0.0.1.tgz
                releaseName: rls-sample-app
                install: true
                waitForExecution: false
                arguments: >
                  --cleanup-on-fail
                  --set partitionValue=$(GetPartition1.truePartition)
                  --set buildId=$(buildId)
                  --set imagePullSecrets=$(secretname)